-- Kantu Floral: trazabilidad de webhooks y reducción de superficie RPC heredada.

create table if not exists public.mercadopago_webhook_events (
  id bigint generated by default as identity primary key,
  request_id text,
  payment_id text,
  order_id text,
  event_type text,
  live_mode boolean,
  processing_result text not null,
  payment_status text,
  received_at timestamptz not null default now()
);

alter table public.mercadopago_webhook_events enable row level security;

revoke all on table public.mercadopago_webhook_events from public, anon, authenticated;
grant select, insert, update, delete on table public.mercadopago_webhook_events to service_role;
grant usage, select on sequence public.mercadopago_webhook_events_id_seq to service_role;

create unique index if not exists mercadopago_webhook_events_request_id_unique
  on public.mercadopago_webhook_events(request_id)
  where request_id is not null;

create index if not exists mercadopago_webhook_events_received_at_idx
  on public.mercadopago_webhook_events(received_at desc);

create index if not exists mercadopago_webhook_events_payment_id_idx
  on public.mercadopago_webhook_events(payment_id)
  where payment_id is not null;

-- La tienda actual utiliza únicamente la firma con coordenadas explícitas.
-- El overload legado que parseaba coordenadas desde delivery_address deja de
-- estar expuesto al navegador para reducir superficie SECURITY DEFINER.
revoke execute on function public.create_order(text, text, text) from public, anon, authenticated;
grant execute on function public.create_order(text, text, text) to service_role;

-- Las funciones privilegiadas sin llamadas no calificadas pueden operar con
-- search_path vacío, reduciendo riesgo de object-shadowing.
alter function public.is_admin() set search_path = '';
alter function public.handle_new_user() set search_path = '';
