-- Kantu Floral: base histórica del sistema de promociones server-side.
-- La migración posterior consolida este modelo con límites y alcance avanzado.

create table if not exists public.promotion_codes (
  id bigint generated by default as identity primary key,
  code text not null,
  description text,
  discount_type text not null,
  discount_value numeric(12,2) not null,
  minimum_subtotal numeric(12,2) not null default 0,
  maximum_discount numeric(12,2),
  starts_at timestamptz,
  ends_at timestamptz,
  active boolean not null default false,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint promotion_codes_code_check check (
    char_length(code) between 3 and 40
    and code = upper(code)
    and code ~ '^[A-Z0-9][A-Z0-9_-]{2,39}$'
  ),
  constraint promotion_codes_description_check check (description is null or char_length(description) <= 240),
  constraint promotion_codes_type_check check (discount_type in ('percent','fixed')),
  constraint promotion_codes_value_check check (discount_value > 0 and (discount_type <> 'percent' or discount_value <= 100)),
  constraint promotion_codes_minimum_check check (minimum_subtotal >= 0),
  constraint promotion_codes_maximum_check check (maximum_discount is null or maximum_discount > 0),
  constraint promotion_codes_window_check check (starts_at is null or ends_at is null or ends_at > starts_at)
);

create unique index if not exists promotion_codes_code_lower_unique
  on public.promotion_codes ((lower(code)));

alter table public.promotion_codes enable row level security;
revoke all on table public.promotion_codes from public, anon, authenticated;
grant select, insert, update, delete on table public.promotion_codes to authenticated;

drop policy if exists "Admins can manage promotion codes" on public.promotion_codes;
create policy "Admins can manage promotion codes"
on public.promotion_codes for all to authenticated
using (public.is_admin()) with check (public.is_admin());

alter table public.orders
  add column if not exists promotion_id bigint,
  add column if not exists promotion_code text,
  add column if not exists discount_amount numeric(12,2) not null default 0;

do $$
begin
  if not exists (
    select 1 from pg_catalog.pg_constraint
    where conname = 'orders_promotion_id_fkey'
      and conrelid = 'public.orders'::regclass
  ) then
    alter table public.orders
      add constraint orders_promotion_id_fkey
      foreign key (promotion_id) references public.promotion_codes(id) on delete set null;
  end if;
end $$;
