-- Kantu Floral: Kantu Match, customer notifications, admin alerts and Libro de Reclamaciones

alter table public.products
    add column if not exists recommendation_priority smallint not null default 0,
    add column if not exists recommendation_audiences text[] not null default '{}',
    add column if not exists recommendation_occasions text[] not null default '{}',
    add column if not exists recommendation_styles text[] not null default '{}';

alter table public.products drop constraint if exists products_recommendation_priority_check;
alter table public.products add constraint products_recommendation_priority_check
    check (recommendation_priority between 0 and 10);

alter table public.products drop constraint if exists products_recommendation_audiences_check;
alter table public.products add constraint products_recommendation_audiences_check
    check (recommendation_audiences <@ array['pareja','mama','amiga','familiar','otro']::text[]);

alter table public.products drop constraint if exists products_recommendation_occasions_check;
alter table public.products add constraint products_recommendation_occasions_check
    check (recommendation_occasions <@ array['cumpleanos','aniversario','amor','perdon','gracias','primera_cita','sorpresa']::text[]);

alter table public.products drop constraint if exists products_recommendation_styles_check;
alter table public.products add constraint products_recommendation_styles_check
    check (recommendation_styles <@ array['romantico','tierno','elegante','impactante','alegre']::text[]);

create table if not exists public.customer_notification_reads (
    user_id uuid not null references auth.users(id) on delete cascade,
    notification_key text not null check (char_length(notification_key) between 3 and 160),
    read_at timestamptz not null default now(),
    primary key (user_id, notification_key)
);

alter table public.customer_notification_reads enable row level security;
revoke all on public.customer_notification_reads from anon, authenticated;
grant select, insert, delete on public.customer_notification_reads to authenticated;

drop policy if exists customer_notification_reads_select_own on public.customer_notification_reads;
create policy customer_notification_reads_select_own on public.customer_notification_reads
for select to authenticated using (user_id = (select auth.uid()));

drop policy if exists customer_notification_reads_insert_own on public.customer_notification_reads;
create policy customer_notification_reads_insert_own on public.customer_notification_reads
for insert to authenticated with check (user_id = (select auth.uid()));

drop policy if exists customer_notification_reads_delete_own on public.customer_notification_reads;
create policy customer_notification_reads_delete_own on public.customer_notification_reads
for delete to authenticated using (user_id = (select auth.uid()));

create table if not exists public.customer_claims (
    id bigint generated by default as identity primary key,
    claim_number text not null unique default (
        'LR-' || to_char(current_date, 'YYYYMMDD') || '-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8))
    ),
    user_id uuid null references auth.users(id) on delete set null,
    complaint_type text not null check (complaint_type in ('reclamo','queja')),
    full_name text not null check (char_length(btrim(full_name)) between 2 and 160),
    document_type text not null check (document_type in ('dni','ce','pasaporte','ruc','otro')),
    document_number text not null check (char_length(btrim(document_number)) between 4 and 30),
    email text not null check (char_length(btrim(email)) between 5 and 254),
    phone text null check (phone is null or char_length(btrim(phone)) between 6 and 40),
    address text not null check (char_length(btrim(address)) between 5 and 300),
    order_reference text null check (order_reference is null or char_length(btrim(order_reference)) <= 80),
    product_service text null check (product_service is null or char_length(btrim(product_service)) <= 200),
    amount_claimed numeric null check (amount_claimed is null or amount_claimed >= 0),
    detail text not null check (char_length(btrim(detail)) between 10 and 4000),
    requested_action text not null check (char_length(btrim(requested_action)) between 5 and 2000),
    status text not null default 'recibido' check (status in ('recibido','en_revision','resuelto')),
    priority text not null default 'normal' check (priority in ('normal','alta','urgente')),
    admin_notes text null check (admin_notes is null or char_length(admin_notes) <= 4000),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    resolved_at timestamptz null
);

create index if not exists customer_claims_status_created_idx
    on public.customer_claims(status, created_at desc);
create index if not exists customer_claims_user_created_idx
    on public.customer_claims(user_id, created_at desc) where user_id is not null;

alter table public.customer_claims enable row level security;
revoke all on public.customer_claims from anon, authenticated;
grant select, update on public.customer_claims to authenticated;

drop policy if exists customer_claims_select_owner_or_admin on public.customer_claims;
create policy customer_claims_select_owner_or_admin on public.customer_claims
for select to authenticated using (
    user_id = (select auth.uid()) or public.is_admin()
);

drop policy if exists customer_claims_update_admin on public.customer_claims;
create policy customer_claims_update_admin on public.customer_claims
for update to authenticated using (public.is_admin()) with check (public.is_admin());

create or replace function private.normalize_customer_claim()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.full_name := btrim(new.full_name);
    new.document_number := upper(btrim(new.document_number));
    new.email := lower(btrim(new.email));
    new.phone := nullif(btrim(coalesce(new.phone, '')), '');
    new.address := btrim(new.address);
    new.order_reference := nullif(btrim(coalesce(new.order_reference, '')), '');
    new.product_service := nullif(btrim(coalesce(new.product_service, '')), '');
    new.detail := btrim(new.detail);
    new.requested_action := btrim(new.requested_action);
    new.admin_notes := nullif(btrim(coalesce(new.admin_notes, '')), '');
    new.updated_at := now();
    if new.status = 'resuelto' and new.resolved_at is null then new.resolved_at := now(); end if;
    if new.status <> 'resuelto' then new.resolved_at := null; end if;
    return new;
end;
$$;

drop trigger if exists customer_claims_normalize on public.customer_claims;
create trigger customer_claims_normalize
before insert or update on public.customer_claims
for each row execute function private.normalize_customer_claim();

create or replace function public.get_customer_notification_feed()
returns table (
    notification_key text,
    kind text,
    title text,
    body text,
    severity text,
    action_url text,
    created_at timestamptz
)
language sql
security definer
set search_path = ''
as $$
    with valid_promotions as (
        select p.*
        from public.promotion_codes p
        where p.active
          and (p.starts_at is null or p.starts_at <= now())
          and (p.ends_at is null or p.ends_at > now())
          and (
              p.max_redemptions is null
              or (select count(*) from public.orders o where o.promotion_id = p.id and o.status <> 'cancelado') < p.max_redemptions
          )
        order by coalesce(p.ends_at, now() + interval '10 years'), p.id desc
        limit 8
    ), featured_products as (
        select p.*
        from public.products p
        where p.active and p.featured and p.stock > 0
        order by p.created_at desc nulls last, p.id desc
        limit 10
    )
    select
        'promo:' || p.id::text,
        'promotion'::text,
        ('Código ' || p.code || ' disponible')::text,
        coalesce(nullif(p.description, ''),
            case when p.discount_type = 'percent'
                then trim(to_char(p.discount_value, 'FM999999990.##')) || '% de descuento'
                else 'S/ ' || trim(to_char(p.discount_value, 'FM999999990.00')) || ' de descuento'
            end
        )::text,
        'benefit'::text,
        '#catalogo'::text,
        p.created_at
    from valid_promotions p
    union all
    select
        'trend:' || p.id::text,
        'trend'::text,
        'Destacado por Kantu'::text,
        (p.name || ' está disponible por S/ ' || trim(to_char(p.price, 'FM999999990.00')))::text,
        'info'::text,
        ('producto.html?id=' || p.id::text)::text,
        coalesce(p.created_at, now())
    from featured_products p
    order by created_at desc
    limit 14;
$$;

revoke all on function public.get_customer_notification_feed() from public;
grant execute on function public.get_customer_notification_feed() to anon, authenticated;

create or replace function public.admin_operational_alerts()
returns table (
    alert_key text,
    kind text,
    severity text,
    title text,
    body text,
    action_view text,
    entity_id text,
    minutes_waiting integer,
    created_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
begin
    if auth.uid() is null then raise exception 'AUTHENTICATION_REQUIRED'; end if;
    if not public.is_admin() then raise exception 'ADMIN_PERMISSION_REQUIRED'; end if;

    return query
    with alerts as (
        select
            'claim:' || c.id::text as alert_key,
            'claim'::text as kind,
            case when extract(epoch from (now() - c.created_at))/60 >= 30 then 'urgent' else 'warning' end::text as severity,
            ('Nuevo ' || c.complaint_type || ' · ' || c.claim_number)::text as title,
            (c.full_name || ' espera revisión: ' || left(c.detail, 180))::text as body,
            'claims'::text as action_view,
            c.id::text as entity_id,
            floor(extract(epoch from (now() - c.created_at))/60)::integer as minutes_waiting,
            c.created_at
        from public.customer_claims c
        where c.status <> 'resuelto'

        union all

        select
            'payment:' || pp.id::text,
            'payment'::text,
            case when extract(epoch from (now() - pp.uploaded_at))/60 >= 10 then 'urgent' else 'warning' end::text,
            ('Verificar pago #' || pp.order_id::text)::text,
            ('El comprobante lleva ' || floor(extract(epoch from (now() - pp.uploaded_at))/60)::integer || ' min esperando revisión.')::text,
            'payments'::text,
            pp.id::text,
            floor(extract(epoch from (now() - pp.uploaded_at))/60)::integer,
            pp.uploaded_at
        from public.payment_proofs pp
        where pp.verification_status in ('uploaded','verifying','needs_review')

        union all

        select
            'order-prep:' || o.id::text,
            'order_delay'::text,
            case when extract(epoch from (now() - coalesce(o.paid_at, o.created_at)))/60 >= 25 then 'urgent' else 'warning' end::text,
            ('Pedido #' || o.id::text || ' aún no entra a preparación')::text,
            ('Pago aprobado hace ' || floor(extract(epoch from (now() - coalesce(o.paid_at, o.created_at)))/60)::integer || ' min.')::text,
            'orders'::text,
            o.id::text,
            floor(extract(epoch from (now() - coalesce(o.paid_at, o.created_at)))/60)::integer,
            coalesce(o.paid_at, o.created_at)
        from public.orders o
        where o.payment_status = 'approved'
          and o.status = 'confirmado'
          and o.prep_started_at is null
          and coalesce(o.paid_at, o.created_at) <= now() - interval '10 minutes'

        union all

        select
            'order-preparing:' || o.id::text,
            'order_delay'::text,
            'urgent'::text,
            ('Pedido #' || o.id::text || ' está demorando en preparación')::text,
            ('Lleva ' || floor(extract(epoch from (now() - o.prep_started_at))/60)::integer || ' min en preparación. Revisa qué está pasando.')::text,
            'orders'::text,
            o.id::text,
            floor(extract(epoch from (now() - o.prep_started_at))/60)::integer,
            o.prep_started_at
        from public.orders o
        where o.status = 'preparando'
          and o.prep_started_at is not null
          and o.prep_started_at <= now() - interval '45 minutes'

        union all

        select
            'order-delivery:' || o.id::text,
            'delivery_delay'::text,
            'urgent'::text,
            ('Delivery del pedido #' || o.id::text || ' está demorando')::text,
            ('Lleva ' || floor(extract(epoch from (now() - o.delivery_started_at))/60)::integer || ' min en camino. Revisa al repartidor o al cliente.')::text,
            'orders'::text,
            o.id::text,
            floor(extract(epoch from (now() - o.delivery_started_at))/60)::integer,
            o.delivery_started_at
        from public.orders o
        where o.status = 'en_camino'
          and o.delivery_started_at is not null
          and extract(epoch from (now() - o.delivery_started_at))/60 > coalesce(o.estimated_delivery_minutes, 60) + 20

        union all

        select
            'stock:' || p.id::text,
            'stock'::text,
            case when p.stock <= 1 then 'urgent' when p.stock <= 3 then 'warning' else 'info' end::text,
            case when p.stock = 0 then ('Sin stock: ' || p.name)::text else ('Stock bajo: ' || p.name)::text end,
            case when p.stock = 0 then 'El producto está agotado y ya no puede venderse.' else ('Quedan solo ' || p.stock::text || ' unidades. Considera reponerlo.') end::text,
            'products'::text,
            p.id::text,
            0,
            coalesce(p.created_at, now())
        from public.products p
        where p.active and p.stock <= 5

        union all

        select
            'scheduled:' || o.id::text || ':' || o.requested_delivery_date::text,
            'scheduled_delivery'::text,
            case
                when o.requested_delivery_date < (now() at time zone 'America/Lima')::date then 'urgent'
                when split_part(coalesce(o.requested_delivery_slot, '23:59'), '-', 1)::time <= (now() at time zone 'America/Lima')::time then 'urgent'
                else 'warning'
            end::text,
            ('Entrega programada pendiente #' || o.id::text)::text,
            ('Entrega solicitada para ' || o.requested_delivery_date::text || coalesce(' · ' || o.requested_delivery_slot, '') || '.')::text,
            'orders'::text,
            o.id::text,
            0,
            o.created_at
        from public.orders o
        where o.requested_delivery_date is not null
          and o.status not in ('entregado','cancelado')
          and o.requested_delivery_date <= (now() at time zone 'America/Lima')::date
    )
    select a.alert_key, a.kind, a.severity, a.title, a.body, a.action_view, a.entity_id, a.minutes_waiting, a.created_at
    from alerts a
    order by
        case a.severity when 'urgent' then 0 when 'warning' then 1 else 2 end,
        a.created_at asc
    limit 100;
end;
$$;

revoke all on function public.admin_operational_alerts() from public;
grant execute on function public.admin_operational_alerts() to authenticated;

create or replace function public.service_submit_customer_claim(
    p_payload jsonb,
    p_fingerprint_hash text,
    p_user_id uuid default null
)
returns table (claim_id bigint, claim_number text)
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_allowed boolean;
    v_retry integer;
    v_row public.customer_claims%rowtype;
begin
    if auth.role() <> 'service_role' then raise exception 'SERVICE_ROLE_REQUIRED'; end if;
    if p_payload is null or jsonb_typeof(p_payload) <> 'object' then raise exception 'INVALID_CLAIM_PAYLOAD'; end if;

    select r.allowed, r.retry_after_seconds into v_allowed, v_retry
    from public.consume_guest_checkout_rate_limit(p_fingerprint_hash, 'complaint_submit', 5, 3600) r;
    if not coalesce(v_allowed, false) then raise exception 'RATE_LIMITED:%', coalesce(v_retry, 3600); end if;

    insert into public.customer_claims (
        user_id, complaint_type, full_name, document_type, document_number,
        email, phone, address, order_reference, product_service, amount_claimed,
        detail, requested_action
    ) values (
        p_user_id,
        lower(coalesce(p_payload->>'complaint_type', '')),
        coalesce(p_payload->>'full_name', ''),
        lower(coalesce(p_payload->>'document_type', '')),
        coalesce(p_payload->>'document_number', ''),
        coalesce(p_payload->>'email', ''),
        nullif(p_payload->>'phone', ''),
        coalesce(p_payload->>'address', ''),
        nullif(p_payload->>'order_reference', ''),
        nullif(p_payload->>'product_service', ''),
        case when nullif(p_payload->>'amount_claimed', '') is null then null else (p_payload->>'amount_claimed')::numeric end,
        coalesce(p_payload->>'detail', ''),
        coalesce(p_payload->>'requested_action', '')
    ) returning * into v_row;

    return query select v_row.id, v_row.claim_number;
exception
    when invalid_text_representation then raise exception 'INVALID_CLAIM_AMOUNT';
end;
$$;

revoke all on function public.service_submit_customer_claim(jsonb,text,uuid) from public, anon, authenticated;
grant execute on function public.service_submit_customer_claim(jsonb,text,uuid) to service_role;

create or replace function public.kantu_growth_health_check()
returns jsonb
language sql
security invoker
set search_path = ''
as $$
select jsonb_build_object(
    'healthy',
        to_regclass('public.customer_claims') is not null
        and to_regclass('public.customer_notification_reads') is not null
        and exists (
            select 1 from information_schema.columns
            where table_schema='public' and table_name='products' and column_name='recommendation_priority'
        )
        and has_function_privilege('anon', 'public.get_customer_notification_feed()', 'EXECUTE')
        and has_function_privilege('authenticated', 'public.get_customer_notification_feed()', 'EXECUTE')
        and has_function_privilege('authenticated', 'public.admin_operational_alerts()', 'EXECUTE')
        and not has_function_privilege('anon', 'public.admin_operational_alerts()', 'EXECUTE')
        and has_function_privilege('service_role', 'public.service_submit_customer_claim(jsonb,text,uuid)', 'EXECUTE')
        and not has_function_privilege('anon', 'public.service_submit_customer_claim(jsonb,text,uuid)', 'EXECUTE')
        and not has_function_privilege('authenticated', 'public.service_submit_customer_claim(jsonb,text,uuid)', 'EXECUTE'),
    'claims_rls', coalesce((select relrowsecurity from pg_catalog.pg_class where oid='public.customer_claims'::regclass), false),
    'notification_reads_rls', coalesce((select relrowsecurity from pg_catalog.pg_class where oid='public.customer_notification_reads'::regclass), false),
    'customer_feed_public', has_function_privilege('anon', 'public.get_customer_notification_feed()', 'EXECUTE'),
    'admin_alerts_anon_blocked', not has_function_privilege('anon', 'public.admin_operational_alerts()', 'EXECUTE'),
    'claim_submit_service_only',
        has_function_privilege('service_role', 'public.service_submit_customer_claim(jsonb,text,uuid)', 'EXECUTE')
        and not has_function_privilege('anon', 'public.service_submit_customer_claim(jsonb,text,uuid)', 'EXECUTE')
        and not has_function_privilege('authenticated', 'public.service_submit_customer_claim(jsonb,text,uuid)', 'EXECUTE')
);
$$;

revoke all on function public.kantu_growth_health_check() from public, anon, authenticated;
grant execute on function public.kantu_growth_health_check() to service_role;
