-- Kantu Floral: inventario auditable, destacados y resumen comercial para Admin.

alter table public.products
  add column if not exists featured boolean not null default false;

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  product_id bigint not null,
  product_name text not null,
  quantity_delta integer not null,
  balance_before integer not null,
  balance_after integer not null,
  source text not null,
  actor_user_id uuid,
  created_at timestamptz not null default now(),
  constraint inventory_movements_balance_check check (balance_before >= 0 and balance_after >= 0),
  constraint inventory_movements_delta_check check (quantity_delta <> 0),
  constraint inventory_movements_source_check check (source in (
    'product_created',
    'admin_adjustment',
    'paid_order',
    'system_adjustment'
  ))
);

create index if not exists inventory_movements_product_created_idx
  on public.inventory_movements(product_id, created_at desc);
create index if not exists inventory_movements_created_idx
  on public.inventory_movements(created_at desc);

alter table public.inventory_movements enable row level security;
revoke all on table public.inventory_movements from public, anon, authenticated;
grant select on table public.inventory_movements to authenticated;
grant all on table public.inventory_movements to service_role;

drop policy if exists "Admins can read inventory movements" on public.inventory_movements;
create policy "Admins can read inventory movements"
on public.inventory_movements
for select
to authenticated
using (public.is_admin());

create or replace function public.log_product_stock_movement()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_before integer;
  v_after integer;
  v_delta integer;
  v_actor uuid;
  v_source text;
begin
  if tg_op = 'INSERT' then
    v_before := 0;
    v_after := coalesce(new.stock, 0);
    v_delta := v_after;
    if v_delta = 0 then return new; end if;
    v_source := 'product_created';
  else
    v_before := coalesce(old.stock, 0);
    v_after := coalesce(new.stock, 0);
    v_delta := v_after - v_before;
    if v_delta = 0 then return new; end if;

    v_actor := auth.uid();
    if v_actor is not null then
      v_source := 'admin_adjustment';
    elsif v_delta < 0 then
      v_source := 'paid_order';
    else
      v_source := 'system_adjustment';
    end if;
  end if;

  insert into public.inventory_movements (
    product_id,
    product_name,
    quantity_delta,
    balance_before,
    balance_after,
    source,
    actor_user_id
  ) values (
    new.id,
    coalesce(nullif(btrim(new.name), ''), 'Producto'),
    v_delta,
    v_before,
    v_after,
    v_source,
    v_actor
  );

  return new;
end;
$$;

revoke all on function public.log_product_stock_movement() from public, anon, authenticated;

drop trigger if exists products_inventory_movement_trigger on public.products;
create trigger products_inventory_movement_trigger
after insert or update of stock on public.products
for each row
execute function public.log_product_stock_movement();

create or replace function public.admin_commerce_overview()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
  v_result jsonb;
begin
  v_user_id := auth.uid();
  if v_user_id is null then raise exception 'AUTHENTICATION_REQUIRED'; end if;
  if not public.is_admin() then raise exception 'ADMIN_PERMISSION_REQUIRED'; end if;

  select jsonb_build_object(
    'metrics', jsonb_build_object(
      'sales_today', coalesce((
        select sum(o.total)
        from public.orders o
        where o.payment_status = 'approved'
          and o.status <> 'cancelado'
          and (coalesce(o.paid_at, o.created_at) at time zone 'America/Lima')::date
            = (now() at time zone 'America/Lima')::date
      ), 0),
      'sales_30d', coalesce((
        select sum(o.total)
        from public.orders o
        where o.payment_status = 'approved'
          and o.status <> 'cancelado'
          and coalesce(o.paid_at, o.created_at) >= now() - interval '30 days'
      ), 0),
      'paid_orders_30d', (
        select count(*)
        from public.orders o
        where o.payment_status = 'approved'
          and o.status <> 'cancelado'
          and coalesce(o.paid_at, o.created_at) >= now() - interval '30 days'
      ),
      'average_ticket_30d', coalesce((
        select avg(o.total)
        from public.orders o
        where o.payment_status = 'approved'
          and o.status <> 'cancelado'
          and coalesce(o.paid_at, o.created_at) >= now() - interval '30 days'
      ), 0),
      'manual_review_count', (
        select count(*)
        from public.payment_proofs pp
        where pp.verification_status in ('uploaded', 'verifying', 'needs_review')
      ),
      'low_stock_count', (
        select count(*) from public.products p
        where p.active = true and coalesce(p.stock, 0) between 1 and 5
      ),
      'out_of_stock_count', (
        select count(*) from public.products p
        where p.active = true and coalesce(p.stock, 0) = 0
      ),
      'avg_prep_minutes_30d', coalesce((
        select round(avg(extract(epoch from (o.ready_for_delivery_at - o.prep_started_at)) / 60.0), 1)
        from public.orders o
        where o.prep_started_at is not null
          and o.ready_for_delivery_at is not null
          and o.ready_for_delivery_at >= now() - interval '30 days'
      ), 0),
      'avg_delivery_minutes_30d', coalesce((
        select round(avg(extract(epoch from (o.delivered_at - o.delivery_started_at)) / 60.0), 1)
        from public.orders o
        where o.delivery_started_at is not null
          and o.delivered_at is not null
          and o.delivered_at >= now() - interval '30 days'
      ), 0)
    ),
    'top_products', coalesce((
      select jsonb_agg(to_jsonb(t) order by t.units_sold desc, t.paid_order_count desc, t.product_id)
      from (
        select p.id as product_id, p.name, p.units_sold, p.paid_order_count, p.stock, p.featured
        from public.products p
        where p.active = true
        order by p.units_sold desc, p.paid_order_count desc, p.id
        limit 6
      ) t
    ), '[]'::jsonb),
    'attention', coalesce((
      select jsonb_agg(to_jsonb(a) order by a.priority, a.created_at desc)
      from (
        select 1 as priority,
               'paid_order_not_confirmed'::text as kind,
               o.id::text as reference_id,
               ('Pedido pagado #' || o.id::text || ' sigue pendiente')::text as title,
               coalesce(o.paid_at, o.created_at) as created_at
        from public.orders o
        where o.payment_status = 'approved' and o.status = 'pendiente'

        union all

        select 2,
               'manual_payment_review',
               pp.id::text,
               ('Comprobante por revisar · pedido #' || pp.order_id::text),
               pp.uploaded_at
        from public.payment_proofs pp
        where pp.verification_status in ('uploaded', 'verifying', 'needs_review')

        union all

        select 3,
               'out_of_stock',
               p.id::text,
               ('Sin stock: ' || p.name),
               coalesce(p.created_at, now())
        from public.products p
        where p.active = true and coalesce(p.stock, 0) = 0

        union all

        select 4,
               'low_stock',
               p.id::text,
               ('Stock bajo (' || p.stock::text || '): ' || p.name),
               coalesce(p.created_at, now())
        from public.products p
        where p.active = true and coalesce(p.stock, 0) between 1 and 3
      ) a
      limit 30
    ), '[]'::jsonb),
    'recent_inventory', coalesce((
      select jsonb_agg(to_jsonb(i) order by i.created_at desc)
      from (
        select m.id, m.product_id, m.product_name, m.quantity_delta,
               m.balance_before, m.balance_after, m.source, m.created_at
        from public.inventory_movements m
        order by m.created_at desc
        limit 20
      ) i
    ), '[]'::jsonb)
  ) into v_result;

  return v_result;
end;
$$;

revoke all on function public.admin_commerce_overview() from public, anon;
grant execute on function public.admin_commerce_overview() to authenticated, service_role;

create or replace function public.kantu_commerce_ops_health_check()
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
select jsonb_build_object(
  'healthy',
    coalesce((select c.relrowsecurity from pg_catalog.pg_class c where c.oid = 'public.inventory_movements'::regclass), false)
    and has_table_privilege('authenticated', 'public.inventory_movements', 'select')
    and not has_table_privilege('authenticated', 'public.inventory_movements', 'insert')
    and not has_table_privilege('authenticated', 'public.inventory_movements', 'update')
    and not has_table_privilege('authenticated', 'public.inventory_movements', 'delete')
    and not has_table_privilege('authenticated', 'public.inventory_movements', 'truncate')
    and exists (
      select 1 from pg_catalog.pg_trigger t
      where t.tgrelid = 'public.products'::regclass
        and t.tgname = 'products_inventory_movement_trigger'
        and not t.tgisinternal
    )
    and to_regprocedure('public.admin_commerce_overview()') is not null
    and exists (
      select 1 from information_schema.columns c
      where c.table_schema = 'public' and c.table_name = 'products' and c.column_name = 'featured'
    ),
  'inventory_rls', coalesce((select c.relrowsecurity from pg_catalog.pg_class c where c.oid = 'public.inventory_movements'::regclass), false),
  'inventory_read_only_for_authenticated',
    has_table_privilege('authenticated', 'public.inventory_movements', 'select')
    and not has_table_privilege('authenticated', 'public.inventory_movements', 'insert')
    and not has_table_privilege('authenticated', 'public.inventory_movements', 'update')
    and not has_table_privilege('authenticated', 'public.inventory_movements', 'delete')
    and not has_table_privilege('authenticated', 'public.inventory_movements', 'truncate'),
  'inventory_trigger', exists (
    select 1 from pg_catalog.pg_trigger t
    where t.tgrelid = 'public.products'::regclass
      and t.tgname = 'products_inventory_movement_trigger'
      and not t.tgisinternal
  ),
  'admin_overview_rpc', to_regprocedure('public.admin_commerce_overview()') is not null,
  'featured_products', exists (
    select 1 from information_schema.columns c
    where c.table_schema = 'public' and c.table_name = 'products' and c.column_name = 'featured'
  )
);
$$;

revoke all on function public.kantu_commerce_ops_health_check() from public, anon, authenticated;
grant execute on function public.kantu_commerce_ops_health_check() to service_role;
