with notes(code,note) as (
  values
  ('n1','Presentación única. Colores y follaje pueden presentar ligeras variaciones según disponibilidad. Incluye tarjeta de cuidados y alimento floral. Precio incluye IGV.'),
  ('n2','Colores y follaje pueden presentar ligeras variaciones según disponibilidad. Incluye tarjeta de cuidados y alimento floral. Precio incluye IGV.'),
  ('n3','Colores y follaje pueden presentar ligeras variaciones según disponibilidad. Incluye tarjeta de cuidados y alimento floral. Flores bajo pedido; consultar disponibilidad. Precio incluye IGV.'),
  ('n4','La peonia se puede conservar por más de 2 años. Colores y follaje pueden variar. Flores bajo pedido; consultar disponibilidad. Precio incluye IGV.'),
  ('n5','Las peonias pueden conservarse por más de 2 años. Colores y follaje pueden variar. Precio incluye IGV.'),
  ('n6','Las peonias se pueden conservar por más de 2 años. Flores bajo pedido; consultar disponibilidad. Precio incluye IGV.'),
  ('n7','Presentación única. Todos los ramos incluyen follaje de acuerdo a disponibilidad.'),
  ('n8','Presentación única. Colores y follaje pueden variar según disponibilidad. La bebida se puede sustituir por café u otra similar en stock. Precio incluye IGV.'),
  ('n9','Presentación única. Colores y follaje pueden variar. Dimensiones de la caja: 15 cm x 15 cm. Precio incluye IGV.'),
  ('n10','Presentación única. Colores y follaje pueden variar. Dimensiones de la caja: 15 cm x 15 cm. Flores bajo pedido; consultar disponibilidad. Precio incluye IGV.'),
  ('n11','Presentación única. Colores y follaje pueden variar según disponibilidad. Precio incluye IGV.'),
  ('n12','Presentación única. Colores y follaje pueden variar. Dimensiones de la caja: 20 cm x 20 cm. Precio incluye IGV.'),
  ('n13','Presentación única. Colores y follaje pueden variar. Flores bajo pedido; consultar disponibilidad. Dimensiones: 15 cm x 15 cm. Precio incluye IGV.'),
  ('n14','Presentación única. Colores y follaje pueden presentar ligeras variaciones según disponibilidad. Incluye tarjeta de cuidados y alimento floral. Flores bajo pedido; consultar disponibilidad. Precio incluye IGV.'),
  ('n15','Presentación única. Consultar colores disponibles. Incluye tarjeta dedicatoria y bolsa de papel kraft. Precio incluye IGV.'),
  ('n16','Presentación única. Incluye tarjeta dedicatoria y bolsa de papel kraft. Precio incluye IGV.'),
  ('n17','El precio puede variar de acuerdo al modelo y tamaño de peluche en stock. Precio incluye IGV.'),
  ('n18','Consultar modelos disponibles. Precio incluye IGV.'),
  ('n19','Consultar colores y modelos disponibles. Precio incluye IGV.'),
  ('n20','Confeti personalizable de acuerdo a stock. Precio incluye IGV.'),
  ('n21','Presentación única. Colores y follaje pueden variar según disponibilidad. Consultar disponibilidad del modelo de peluche. Precio incluye IGV.')
),
catalog(idx,name,description,price,category,size,note_code) as (
  values
  (1,'Caja de 1 rosa','Selección de 1 rosa premium, acompañada de fino follaje.',29,'cajas','M','n1'),
  (2,'Caja 3 rosas','Selección de 3 rosas premium acompañadas de fino follaje.',49,'cajas','M','n1'),
  (3,'Caja de 6 rosas','Selección de 6 rosas premium, acompañadas de fino follaje.',79,'cajas','M','n1'),
  (4,'Caja de 9 rosas','Selección de 3 rosas premium acompañadas de fino follaje.',109,'cajas','M','n1'),
  (5,'Caja Rose 3 rosas','Selección de 3 rosas premium, acompañadas de fino follaje.',49,'cajas','M','n1'),
  (6,'Caja Rose 6 rosas','Selección de 6 rosas premium acompañadas de fino follaje.',79,'cajas','M','n1'),
  (7,'Caja 12 rosas','Selección de 12 rosas premium acompañadas de fino follaje.',129,'cajas','M','n1'),
  (8,'Caja 1 tulipán','Selección de 1 tulipán premium acompañado de fino follaje.',39,'cajas','M','n1'),
  (9,'Caja 3 tulipanes','Selección de 3 tulipanes premium acompañados de fino follaje.',79,'cajas','M','n1'),
  (10,'Caja 6 tulipanes','Selección de 6 tulipanes premium acompañados de fino follaje.',119,'cajas','M','n1'),
  (11,'Ramo Swetty','Mixtura de 3 rosas, astromelias y minirosas.',59,'ramos','S','n2'),
  (12,'Ramo Sky','Ramo de 3 rosas premium acompañado de fino follaje.',39,'rosas','S','n2'),
  (13,'Ramo Mix','Mix de flores de temporada: astromelias, margaritas, mini rosas, nardo, una rosa, coronado con un hermoso crisantemo.',59,'ramos','S','n2'),
  (14,'Ramo Sue','Mixtura de 2 tulipanes premium, 3 rosas y lisianthus sobre una hermosa hortensia acompañada de fino follaje.',129,'ramos','M','n2'),
  (15,'Ramo Carolina','Selección de 5 rosas premium y minirosas acompañado de fino follaje.',79,'rosas','S','n2'),
  (16,'Ramo Bloom','Mixtura de 6 rosas, claveles y margaritas acompañada de fino follaje.',109,'ramos','L','n3'),
  (17,'Ramo Seven','Ramo de 7 rosas premium acompañado de fino follaje.',69,'rosas','S','n2'),
  (18,'Ramo Aravella','Selección de 5 rosas y claveles acompañados de fino follaje.',79,'ramos','S','n3'),
  (19,'Ramo Annie','Selección de 9 rosas de primera calidad acompañado de fino follaje.',89,'rosas','M','n2'),
  (20,'Ramo Lu','Mixtura de 12 rosas y minirosas acompañada de fino follaje.',149,'rosas','L','n2'),
  (21,'Ramo 24 rosas','Selección de 24 rosas premium acompañado de fino follaje.',189,'rosas','M','n3'),
  (22,'Ramo 50 rosas','Selección de 50 rosas premium acompañado de fino follaje.',259,'ramos_buchones','XL','n3'),
  (23,'Ramo 100 rosas','Selección de 100 rosas premium acompañado de lisianthus.',469,'ramos_buchones','XXL','n3'),
  (24,'Ramo Selena','Ramo de 3 varillas de lirios premium acompañado de fino follaje.',79,'ramos','M','n3'),
  (25,'Ramo Lily','Selección de 5 varillas de lirios deluxe acompañadas de astromelias y fino follaje.',139,'ramos','L','n3'),
  (26,'Ramo Aurora','Selección de 24 rosas premium y 6 lirios perfumados acompañado de dogos con fino follaje.',229,'ramos','L','n3'),
  (27,'Ramo Lia','Selección de 5 varillas de lirios deluxe y 10 rosas acompañadas de dogos y fino follaje.',189,'ramos','L','n3'),
  (28,'Ramo Sunshine','Ramo de 3 girasoles premium acompañado de fino follaje.',59,'girasoles','M','n3'),
  (29,'Ramo Alegría','Mixtura de 5 girasoles pequeños, astromelias y claveles, acompañada de un fino follaje.',79,'girasoles','L','n3'),
  (30,'Ramo Rue','Selección de margaritas, lisianthus y una rosa premium acompañado de fino follaje.',59,'ramos','M','n3'),
  (31,'Ramo Pretty','Selección de margaritas, lisianthus, una rosa y 3 tulipanes premium, sobre una hortensia, acompañada de fino follaje.',139,'ramos','M','n3'),
  (32,'Ramo Blue','Selección de 3 hortensias, rosas y claveles premium acompañado de fino follaje.',119,'ramos','L','n3'),
  (33,'Ramo Ana','Selección de hortensias y 7 rosas premium acompañada de fino follaje.',89,'ramos','L','n3'),
  (34,'Ramo Rafaela','Mixtura de 7 rosas, hortensia y claveles rellenos acompañada de fino follaje.',89,'ramos','M','n3'),
  (35,'Ramo Marie','Mixtura de 12 rosas, hortensias y claveles, acompañada de fino follaje.',169,'ramos','L','n3'),
  (36,'Ramo Lux','Selección de 3 claveles rellenos y una gerbera, coronado con una peonia preservada premium.',99,'ramos','S','n4'),
  (37,'Ramo Infinity','Selección de 5 peonías preservadas premium acompañadas de flores secas.',349,'flores','M','n5'),
  (38,'Ramo Celeste','Ramo de 2 peonias preservadas premium, hortensia, rosas y claveles acompañado de fino follaje.',199,'flores','M','n6'),
  (39,'Ramo Luxury','Selección de una peonia preservada acompañada de 5 rosas premium, 2 gerberas, claveles y fino follaje.',139,'flores','M','n6'),
  (40,'Ramo 7 tulipanes','Selección de 7 tulipanes premium acompañado de fino follaje. Colores de acuerdo a disponibilidad.',119,'tulipanes','M','n3'),
  (41,'Ramo Glamour','Selección de 5 tulipanes premium y mini rosas acompañada de fino follaje. Colores de acuerdo a disponibilidad.',149,'tulipanes','M','n3'),
  (42,'20 tulipanes','Selección de 20 tulipanes premium acompañado de fino follaje. Colores de acuerdo a disponibilidad.',299,'tulipanes','L','n3'),
  (43,'Ramo Tulip','Selección de 12 tulipanes premium, acompañada de un fino follaje. Colores de acuerdo a disponibilidad.',209,'tulipanes','M','n3'),
  (44,'Ramo Bella','Ramo de 7 rosas inglesas premium y mini rosas acompañado de fino follaje.',99,'ramos','M','n3'),
  (45,'Ramo Elegant','Selección de 7 ranúnculos deluxe acompañados de minirosas y fino follaje.',99,'ramos','M','n3'),
  (46,'Ramo Carlie','Mixtura de 6 gerberas premium, rosas, margaritas y claveles acompañado de fino follaje.',119,'ramos','L','n3'),
  (47,'Ramo Girl','Selección de 5 gerberas premium, acompañadas de un fino follaje.',69,'ramos','M','n3'),
  (48,'Ramo 1 girasol','Ramo de 1 girasol con follaje de acuerdo a disponibilidad.',29,'girasoles','M','n7'),
  (49,'Ramo 5 girasoles','Ramo de 5 girasoles con follaje de acuerdo a disponibilidad.',89,'girasoles','M','n7'),
  (50,'Ramo 8 girasoles','Ramo de 8 girasoles con follaje de acuerdo a disponibilidad.',109,'girasoles','M','n7'),
  (51,'Ramo 15 girasoles','Ramo de 15 girasoles con follaje de acuerdo a disponibilidad.',149,'girasoles','M','n7'),
  (52,'Ramo 3 tulipanes','Ramo de 3 tulipanes con follaje de acuerdo a disponibilidad.',79,'tulipanes','M','n7'),
  (53,'Ramo 6 tulipanes','Ramo de 6 tulipanes con follaje de acuerdo a disponibilidad.',119,'tulipanes','M','n7'),
  (54,'Ramo 10 tulipanes','Ramo de 10 tulipanes con follaje de acuerdo a disponibilidad.',189,'tulipanes','M','n7'),
  (55,'Drink Box Love','Selección de 5 rosas de primera calidad acompañado de fino follaje y un vino semiseco Borgoña Viña Vieja.',79,'box','M','n8'),
  (56,'Drink Box Rose','Mixtura de 4 rosas, claveles, astromelias y un vino semiseco Malbec Viña Vieja.',69,'box','M','n8'),
  (57,'Drink Box Sun','Mix de 5 mini girasoles, astromelias y margaritas, acompañado de fino follaje y una refrescante Sangría Viña Vieja.',79,'box','M','n8'),
  (58,'Drink Box Bloom','Mixtura de 4 rosas, margaritas, claveles y una deliciosa Sangría Viña Vieja.',79,'box','M','n8'),
  (59,'Box Lovely','Mixtura de rosas, astromelias y mini rosas presentadas en una hermosa caja de fibrocartón.',139,'box','M','n9'),
  (60,'Box Red','Selección de 12 rosas premium acompañado de fino follaje.',129,'box','M','n9'),
  (61,'Box Angel','Selección de 15 rosas premium acompañado de fino follaje.',149,'box','M','n9'),
  (62,'Box Coronita','Box de 10 rosas azules y dos cervezas Coronita.',119,'box','M','n9'),
  (63,'Box Ferrero','Box de 10 rosas azules o color a elegir, coronado de 6 bombones Ferrero Rocher.',129,'box','M','n10'),
  (64,'Box Bloom','Box mixtura de rosas, margaritas, hortensia y fino follaje.',139,'box','M','n10'),
  (65,'Box Sunshine','Box de 5-6 girasoles premium acompañado de fino follaje.',89,'box','M','n10'),
  (66,'Box Glam','Box con 20 tulipanes premium y fino follaje.',319,'box','M','n10'),
  (67,'Hearth Box Ferrero','Box en forma de corazón con 15 rosas y 10 bombones Ferrero, acompañado de fino follaje.',219,'box','M','n11'),
  (68,'Box Burgos','Selección de 5 rosas azules premium acompañada de 10 bombones Ferrero Rocher y un licor crema Burgos.',179,'box','M','n11'),
  (69,'Box Bear Love','Selección de 25 rosas premium acompañado de fino follaje, un osito de peluche y globo corazón grande metálico.',219,'box','M','n12'),
  (70,'Hearth Box','Selección de 10 rosas premium y minirosas acompañadas de fino follaje.',229,'box','M','n11'),
  (71,'Box Magia','Mixtura de lirios, rosas y astromelias acompañado de fino follaje.',279,'box','M','n11'),
  (72,'Mini Flower Bag','Selección de 9 rosas de primera calidad acompañado de fino follaje, presentadas en una hermosa cartera de folcote.',89,'box','M','n13'),
  (73,'Canasta Happy','Mixtura de lirios, rosas, margaritas y un crisantemo acompañado de fino follaje.',189,'canasta','M','n14'),
  (74,'Canasta I Love U','Mixtura de hortensias, gerberas, margaritas y rosas acompañada de fino follaje.',189,'canasta','M','n14'),
  (75,'Canasta Primavera','Mixtura de rosas, mini girasoles, margaritas y astromelias acompañado de fino follaje.',179,'canasta','M','n14'),
  (76,'Canasta Mimi','Selección de 13 rosas premium y margaritas acompañadas de fino follaje en una canasta pequeña.',159,'canasta','M','n1'),
  (77,'Base Alegría','Mixtura de rosas, minirosas y minigirasoles acompañado de fino follaje en una base cerámica mediana.',219,'flores','M','n1'),
  (78,'Base Princess','Mixtura de 5 rosas, astromelias y mini rosas presentadas en una hermosa base de cerámica.',129,'flores','M','n14'),
  (79,'Base Peony','Peonia preservada acompañada de flores secas elegantes en base de cerámica. Duración de 3 a 5 años.',159,'flores','M','n15'),
  (80,'Base Rose','Rosa preservada acompañada de flores secas elegantes en base de cerámica. Duración de 3 a 5 años.',139,'flores','M','n15'),
  (81,'Infinit Bloom','Rosa preservada encapsulada en una cúpula de vidrio, acompañada de flores secas elegantes. Duración de 3 a 5 años.',159,'flores','M','n15'),
  (82,'Infinit Pastel','Rosa preservada multicolor encapsulada en una cúpula de vidrio, acompañada de flores secas elegantes. Duración de 3 a 5 años.',189,'flores','M','n16'),
  (83,'Infinit Sunshine','Mini girasol preservado encapsulado en una cúpula de vidrio, acompañado de flores secas elegantes. Duración de 3 a 5 años.',169,'flores','M','n16'),
  (84,'Peluche hipoalergénico pequeño','Peluche hipoalergénico. Aproximadamente 15 cm. Consultar modelos disponibles.',29,'complementos','S','n17'),
  (85,'Peluche hipoalergénico mediano','Peluche hipoalergénico. Aproximadamente 30 cm. Consultar modelos disponibles.',79,'complementos','M','n17'),
  (86,'Peluche hipoalergénico grande','Peluche hipoalergénico. Aproximadamente 50 cm. Consultar modelos disponibles.',109,'complementos','L','n17'),
  (87,'Topper temático pequeño','Topper temático de trupan dorado. Consultar modelos disponibles.',7,'complementos','S','n18'),
  (88,'Topper temático mediano','Topper temático de trupan dorado. Consultar modelos disponibles.',15,'complementos','M','n18'),
  (89,'Globo metálico mini','Globo metálico con aire. Consultar colores y modelos disponibles.',3,'complementos','S','n19'),
  (90,'Globo metálico pequeño','Globo metálico con aire. Consultar colores y modelos disponibles.',7,'complementos','M','n19'),
  (91,'Globo metálico grande','Globo metálico con aire. Consultar colores y modelos disponibles.',15,'complementos','L','n19'),
  (92,'Globo burbuja grande','Globo burbuja con aire. Confeti del interior personalizable de acuerdo a stock.',20,'complementos','L','n20'),
  (93,'Ramo Exitosa','Selección de 5 rosas premium y minirosas acompañado de fino follaje y un hermoso osito graduado.',99,'complementos','M','n21'),
  (94,'Ramo Exitoso','Selección de 3 girasoles deluxe acompañadas de astromelias, fino follaje y un osito graduado.',99,'complementos','M','n21'),
  (95,'Pack Graduado','Diseño en base de cerámica blanca con flores secas naturales en tonos suaves, un osito graduado de 35 cm y topper dorado.',129,'complementos','M','n21'),
  (96,'Pack Congrats','Ramo de 24 rosas premium acompañado de fino follaje y osito graduado de 35 cm.',229,'complementos','M','n21')
),
prepared as (
  select
    c.name,
    c.description,
    c.price,
    c.category,
    format('https://raw.githubusercontent.com/Chemsito/Kantu-Floral/main/assets/catalog/blume-2026/%s.webp', lpad(c.idx::text,3,'0')) as image,
    'Catálogo BLUME 2026'::text as tag,
    c.size,
    n.note,
    10::integer as stock,
    true as active
  from catalog c
  join notes n on n.code = c.note_code
)
insert into public.products(name,description,price,category,image,tag,size,note,stock,active)
select p.name,p.description,p.price,p.category,p.image,p.tag,p.size,p.note,p.stock,p.active
from prepared p
where not exists (
  select 1
  from public.products existing
  where existing.name = p.name
    and existing.tag = p.tag
);
