-- Kantu Floral: promociones/cupones server-side.
-- No crea códigos comerciales por defecto: Admin debe definirlos explícitamente.

create table if not exists public.promotion_codes (
  id bigint generated by default as identity primary key,
  code text not null,
  description text,
  discount_type text not null,
  discount_value numeric(12,2) not null,
  minimum_subtotal numeric(12,2) not null default 0,
  maximum_discount numeric(12,2),
  starts_at timestamp with time zone,
  ends_at timestamp with time zone,
  active boolean not null default false,
  created_by uuid,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint promotion_codes_code_check check (
    char_length(code) between 3 and 40
    and code = upper(code)
    and code ~ '^[A-Z0-9][A-Z0-9_-]{2,39}$'
  ),
  constraint promotion_codes_description_check check (
    description is null or char_length(description) <= 240
  ),
  constraint promotion_codes_type_check check (discount_type in ('percent','fixed')),
  constraint promotion_codes_value_check check (
    discount_value > 0
    and (discount_type <> 'percent' or discount_value <= 100)
  ),
  constraint promotion_codes_minimum_check check (minimum_subtotal >= 0),
  constraint promotion_codes_maximum_check check (maximum_discount is null or maximum_discount > 0),
  constraint promotion_codes_window_check check (
    starts_at is null or ends_at is null or ends_at > starts_at
  )
);

create unique index if not exists promotion_codes_code_lower_unique
  on public.promotion_codes ((lower(code)));

alter table public.promotion_codes enable row level security;

revoke all on table public.promotion_codes from public, anon, authenticated;
grant select, insert, update, delete on table public.promotion_codes to authenticated;

do $$
begin
  if to_regclass('public.promotion_codes_id_seq') is not null then
    execute 'revoke all on sequence public.promotion_codes_id_seq from public, anon, authenticated';
    execute 'grant usage, select on sequence public.promotion_codes_id_seq to authenticated';
  end if;
end $$;

drop policy if exists "Admins can manage promotion codes" on public.promotion_codes;
create policy "Admins can manage promotion codes"
on public.promotion_codes
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

alter table public.orders
  add column if not exists promotion_id bigint,
  add column if not exists promotion_code text,
  add column if not exists discount_amount numeric(12,2) not null default 0;

do $$
begin
  if not exists (
    select 1 from pg_catalog.pg_constraint
    where conname = 'orders_promotion_id_fkey'
      and conrelid = 'public.orders'::regclass
  ) then
    alter table public.orders
      add constraint orders_promotion_id_fkey
      foreign key (promotion_id)
      references public.promotion_codes(id)
      on delete set null;
  end if;

  if not exists (
    select 1 from pg_catalog.pg_constraint
    where conname = 'orders_discount_amount_check'
      and conrelid = 'public.orders'::regclass
  ) then
    alter table public.orders
      add constraint orders_discount_amount_check
      check (discount_amount >= 0 and discount_amount <= subtotal);
  end if;
end $$;

create or replace function public.calculate_promotion_discount(
  p_code text,
  p_subtotal numeric
)
returns table(
  promotion_id bigint,
  normalized_code text,
  promotion_description text,
  valid boolean,
  discount_amount numeric,
  reason text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_code text;
  v_promotion public.promotion_codes%rowtype;
  v_discount numeric(12,2) := 0;
begin
  v_code := upper(btrim(coalesce(p_code, '')));

  if v_code = '' or char_length(v_code) > 40 then
    return query select null::bigint, null::text, null::text, false, 0::numeric, 'PROMOTION_NOT_AVAILABLE'::text;
    return;
  end if;

  if p_subtotal is null or p_subtotal < 0 then
    return query select null::bigint, v_code, null::text, false, 0::numeric, 'INVALID_SUBTOTAL'::text;
    return;
  end if;

  select p.*
    into v_promotion
    from public.promotion_codes p
   where lower(p.code) = lower(v_code)
   limit 1;

  if not found
     or not coalesce(v_promotion.active, false)
     or (v_promotion.starts_at is not null and now() < v_promotion.starts_at)
     or (v_promotion.ends_at is not null and now() >= v_promotion.ends_at)
  then
    return query select null::bigint, v_code, null::text, false, 0::numeric, 'PROMOTION_NOT_AVAILABLE'::text;
    return;
  end if;

  if p_subtotal < v_promotion.minimum_subtotal then
    return query
    select v_promotion.id, v_promotion.code, v_promotion.description, false, 0::numeric, 'PROMOTION_MINIMUM_NOT_MET'::text;
    return;
  end if;

  if v_promotion.discount_type = 'percent' then
    v_discount := round((p_subtotal * v_promotion.discount_value / 100.0)::numeric, 2);
    if v_promotion.maximum_discount is not null then
      v_discount := least(v_discount, v_promotion.maximum_discount);
    end if;
  elsif v_promotion.discount_type = 'fixed' then
    v_discount := least(v_promotion.discount_value, p_subtotal);
  else
    return query
    select v_promotion.id, v_promotion.code, v_promotion.description, false, 0::numeric, 'PROMOTION_NOT_AVAILABLE'::text;
    return;
  end if;

  v_discount := greatest(0::numeric, least(round(v_discount, 2), p_subtotal));

  return query
  select v_promotion.id, v_promotion.code, v_promotion.description, true, v_discount, null::text;
end;
$$;

revoke all on function public.calculate_promotion_discount(text,numeric) from public, anon, authenticated;
grant execute on function public.calculate_promotion_discount(text,numeric) to service_role;

create or replace function public.quote_promotion_code(p_code text)
returns table(
  code text,
  valid boolean,
  discount_amount numeric,
  subtotal numeric,
  discounted_subtotal numeric,
  reason text,
  description text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
  v_subtotal numeric(12,2) := 0;
  v_count integer := 0;
  v_item record;
  v_promotion record;
begin
  v_user_id := auth.uid();
  if v_user_id is null then raise exception 'AUTHENTICATION_REQUIRED'; end if;

  for v_item in
    select ci.quantity, p.price, p.stock, p.active
      from public.cart_items ci
      join public.products p on p.id = ci.product_id
     where ci.user_id = v_user_id
  loop
    v_count := v_count + 1;
    if v_item.quantity is null or v_item.quantity <= 0 then raise exception 'INVALID_CART'; end if;
    if v_item.active is not true then raise exception 'PRODUCT_NOT_AVAILABLE'; end if;
    if v_item.stock is null or v_item.stock < v_item.quantity then raise exception 'INSUFFICIENT_STOCK'; end if;
    v_subtotal := v_subtotal + (v_item.price * v_item.quantity);
  end loop;

  if v_count = 0 then raise exception 'CART_EMPTY'; end if;

  select * into v_promotion
  from public.calculate_promotion_discount(p_code, v_subtotal);

  return query
  select
    coalesce(v_promotion.normalized_code, upper(btrim(coalesce(p_code, '')))),
    coalesce(v_promotion.valid, false),
    coalesce(v_promotion.discount_amount, 0::numeric),
    v_subtotal,
    greatest(0::numeric, v_subtotal - coalesce(v_promotion.discount_amount, 0::numeric)),
    v_promotion.reason,
    v_promotion.promotion_description;
end;
$$;

revoke all on function public.quote_promotion_code(text) from public, anon;
grant execute on function public.quote_promotion_code(text) to authenticated;

create or replace function public.create_order(
  p_customer_name text,
  p_customer_phone text,
  p_delivery_address text,
  p_delivery_lat numeric,
  p_delivery_lng numeric,
  p_recipient_name text,
  p_recipient_phone text,
  p_gift_message text,
  p_is_surprise boolean,
  p_requested_delivery_date date,
  p_requested_delivery_slot text,
  p_promotion_code text
)
returns table(
  order_id bigint,
  total numeric,
  subtotal numeric,
  delivery_fee numeric,
  delivery_distance_km numeric,
  estimated_delivery_minutes integer,
  discount_amount numeric
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
  v_order_id bigint;
  v_subtotal numeric := 0;
  v_total numeric := 0;
  v_delivery_fee numeric := 0;
  v_delivery_distance numeric := 0;
  v_estimated_minutes integer := 20;
  v_service_available boolean := false;
  v_item record;
  v_item_count integer := 0;
  v_recipient_name text;
  v_recipient_phone text;
  v_gift_message text;
  v_delivery_slot text;
  v_schedule_enabled boolean := false;
  v_min_lead_hours integer := 0;
  v_max_days_ahead integer := 30;
  v_slots text[] := '{}'::text[];
  v_now_local timestamp without time zone := timezone('America/Lima', now());
  v_today date;
  v_slot_start time without time zone;
  v_promotion record;
  v_promotion_id bigint := null;
  v_promotion_code text := null;
  v_discount_amount numeric(12,2) := 0;
begin
  v_user_id := auth.uid();
  if v_user_id is null then raise exception 'AUTHENTICATION_REQUIRED'; end if;
  if nullif(btrim(p_customer_name), '') is null then raise exception 'CUSTOMER_NAME_REQUIRED'; end if;
  if nullif(btrim(p_customer_phone), '') is null then raise exception 'CUSTOMER_PHONE_REQUIRED'; end if;
  if nullif(btrim(p_delivery_address), '') is null then raise exception 'DELIVERY_ADDRESS_REQUIRED'; end if;

  v_recipient_name := coalesce(nullif(btrim(p_recipient_name), ''), btrim(p_customer_name));
  v_recipient_phone := coalesce(nullif(btrim(p_recipient_phone), ''), btrim(p_customer_phone));
  v_gift_message := nullif(btrim(p_gift_message), '');
  v_delivery_slot := nullif(btrim(p_requested_delivery_slot), '');
  v_today := v_now_local::date;

  if char_length(v_recipient_name) > 120 then raise exception 'RECIPIENT_NAME_TOO_LONG'; end if;
  if char_length(v_recipient_phone) > 40 then raise exception 'RECIPIENT_PHONE_TOO_LONG'; end if;
  if v_gift_message is not null and char_length(v_gift_message) > 500 then raise exception 'GIFT_MESSAGE_TOO_LONG'; end if;

  select s.scheduling_enabled, s.min_lead_hours, s.max_days_ahead, s.slots
    into v_schedule_enabled, v_min_lead_hours, v_max_days_ahead, v_slots
    from public.delivery_schedule_settings s
   where s.id = 1;

  if p_requested_delivery_date is null and v_delivery_slot is not null then
    raise exception 'DELIVERY_DATE_REQUIRED_FOR_SLOT';
  end if;

  if p_requested_delivery_date is not null then
    if not coalesce(v_schedule_enabled, false) then raise exception 'DELIVERY_SCHEDULING_DISABLED'; end if;
    if p_requested_delivery_date < v_today then raise exception 'INVALID_DELIVERY_DATE'; end if;
    if p_requested_delivery_date > (v_today + coalesce(v_max_days_ahead, 30)) then raise exception 'DELIVERY_DATE_TOO_FAR'; end if;
    if v_delivery_slot is null then raise exception 'DELIVERY_SLOT_REQUIRED'; end if;
    if not (v_delivery_slot = any(coalesce(v_slots, '{}'::text[]))) then raise exception 'INVALID_DELIVERY_SLOT'; end if;
    if v_delivery_slot !~ '^(?:[01][0-9]|2[0-3]):[0-5][0-9]-(?:[01][0-9]|2[0-3]):[0-5][0-9]$' then raise exception 'INVALID_DELIVERY_SLOT'; end if;

    v_slot_start := split_part(v_delivery_slot, '-', 1)::time;
    if (p_requested_delivery_date::timestamp + v_slot_start)
       < (v_now_local + make_interval(hours => coalesce(v_min_lead_hours, 0))) then
      raise exception 'DELIVERY_SLOT_TOO_SOON';
    end if;
  end if;

  select q.distance_km, q.delivery_fee, q.estimated_minutes, q.service_available
    into v_delivery_distance, v_delivery_fee, v_estimated_minutes, v_service_available
    from public.quote_delivery_fee(p_delivery_lat, p_delivery_lng) q;

  if not coalesce(v_service_available, false) then raise exception 'DELIVERY_OUT_OF_RANGE'; end if;

  for v_item in
    select ci.product_id, ci.quantity, p.price, p.stock, p.active
      from public.cart_items ci
      join public.products p on p.id = ci.product_id
     where ci.user_id = v_user_id
     for update of ci, p
  loop
    v_item_count := v_item_count + 1;
    if v_item.quantity is null or v_item.quantity <= 0 then raise exception 'INVALID_CART'; end if;
    if v_item.active is not true then raise exception 'PRODUCT_NOT_AVAILABLE'; end if;
    if v_item.stock is null or v_item.stock < v_item.quantity then raise exception 'INSUFFICIENT_STOCK'; end if;
    v_subtotal := v_subtotal + (v_item.price * v_item.quantity);
  end loop;

  if v_item_count = 0 then raise exception 'CART_EMPTY'; end if;

  if nullif(btrim(coalesce(p_promotion_code, '')), '') is not null then
    select * into v_promotion
      from public.calculate_promotion_discount(p_promotion_code, v_subtotal);

    if not coalesce(v_promotion.valid, false) then
      raise exception '%', coalesce(v_promotion.reason, 'PROMOTION_NOT_AVAILABLE');
    end if;

    v_promotion_id := v_promotion.promotion_id;
    v_promotion_code := v_promotion.normalized_code;
    v_discount_amount := coalesce(v_promotion.discount_amount, 0::numeric);
  end if;

  v_total := greatest(0::numeric, v_subtotal + v_delivery_fee - v_discount_amount);

  insert into public.orders (
    user_id, total, subtotal, delivery_fee, delivery_distance_km, delivery_lat, delivery_lng,
    estimated_delivery_minutes, status, customer_name, customer_phone, delivery_address,
    recipient_name, recipient_phone, gift_message, is_surprise,
    requested_delivery_date, requested_delivery_slot,
    promotion_id, promotion_code, discount_amount
  ) values (
    v_user_id, v_total, v_subtotal, v_delivery_fee, v_delivery_distance, p_delivery_lat, p_delivery_lng,
    v_estimated_minutes, 'pendiente', btrim(p_customer_name), btrim(p_customer_phone), btrim(p_delivery_address),
    v_recipient_name, v_recipient_phone, v_gift_message, coalesce(p_is_surprise, false),
    p_requested_delivery_date, v_delivery_slot,
    v_promotion_id, v_promotion_code, v_discount_amount
  ) returning id into v_order_id;

  insert into public.order_items (order_id, product_id, quantity, unit_price)
  select v_order_id, ci.product_id, ci.quantity, p.price
    from public.cart_items ci
    join public.products p on p.id = ci.product_id
   where ci.user_id = v_user_id;

  delete from public.cart_items where user_id = v_user_id;

  return query
  select v_order_id, v_total, v_subtotal, v_delivery_fee, v_delivery_distance, v_estimated_minutes, v_discount_amount;
end;
$$;

revoke all on function public.create_order(text,text,text,numeric,numeric,text,text,text,boolean,date,text,text) from public, anon;
grant execute on function public.create_order(text,text,text,numeric,numeric,text,text,text,boolean,date,text,text) to authenticated;

-- Compatibilidad: la firma anterior continúa funcionando sin promoción.
create or replace function public.create_order(
  p_customer_name text,
  p_customer_phone text,
  p_delivery_address text,
  p_delivery_lat numeric,
  p_delivery_lng numeric,
  p_recipient_name text,
  p_recipient_phone text,
  p_gift_message text,
  p_is_surprise boolean,
  p_requested_delivery_date date,
  p_requested_delivery_slot text
)
returns table(
  order_id bigint,
  total numeric,
  subtotal numeric,
  delivery_fee numeric,
  delivery_distance_km numeric,
  estimated_delivery_minutes integer
)
language sql
set search_path = ''
as $$
  select c.order_id, c.total, c.subtotal, c.delivery_fee, c.delivery_distance_km, c.estimated_delivery_minutes
  from public.create_order(
    p_customer_name,
    p_customer_phone,
    p_delivery_address,
    p_delivery_lat,
    p_delivery_lng,
    p_recipient_name,
    p_recipient_phone,
    p_gift_message,
    p_is_surprise,
    p_requested_delivery_date,
    p_requested_delivery_slot,
    null::text
  ) c;
$$;

create or replace function public.kantu_promotions_health_check()
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
select jsonb_build_object(
  'healthy',
    coalesce((select c.relrowsecurity from pg_catalog.pg_class c where c.oid='public.promotion_codes'::regclass), false)
    and to_regprocedure('public.quote_promotion_code(text)') is not null
    and to_regprocedure('public.create_order(text,text,text,numeric,numeric,text,text,text,boolean,date,text,text)') is not null
    and exists (select 1 from information_schema.columns where table_schema='public' and table_name='orders' and column_name='discount_amount')
    and exists (select 1 from information_schema.columns where table_schema='public' and table_name='orders' and column_name='promotion_code')
    and not has_table_privilege('anon', 'public.promotion_codes', 'SELECT')
    and not has_table_privilege('authenticated', 'public.promotion_codes', 'TRUNCATE'),
  'promotion_rls', coalesce((select c.relrowsecurity from pg_catalog.pg_class c where c.oid='public.promotion_codes'::regclass), false),
  'quote_rpc', to_regprocedure('public.quote_promotion_code(text)') is not null,
  'create_order_promotion_rpc', to_regprocedure('public.create_order(text,text,text,numeric,numeric,text,text,text,boolean,date,text,text)') is not null,
  'orders_discount_columns',
    exists (select 1 from information_schema.columns where table_schema='public' and table_name='orders' and column_name='discount_amount')
    and exists (select 1 from information_schema.columns where table_schema='public' and table_name='orders' and column_name='promotion_code'),
  'anon_promotion_table_blocked', not has_table_privilege('anon', 'public.promotion_codes', 'SELECT'),
  'authenticated_no_truncate', not has_table_privilege('authenticated', 'public.promotion_codes', 'TRUNCATE')
);
$$;

revoke all on function public.kantu_promotions_health_check() from public, anon, authenticated;
grant execute on function public.kantu_promotions_health_check() to service_role;
