-- Kantu Floral: fechas especiales privadas del cliente.
-- Son recordatorios dentro de la experiencia Kantu; no envían WhatsApp ni mensajes externos.

create table if not exists public.special_date_reminders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  label text not null,
  recipient_name text,
  occasion text not null default 'other',
  event_month smallint not null,
  event_day smallint not null,
  reminder_days_before smallint not null default 7,
  notes text,
  active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint special_date_reminders_label_check check (char_length(btrim(label)) between 1 and 120),
  constraint special_date_reminders_recipient_check check (recipient_name is null or char_length(recipient_name) <= 120),
  constraint special_date_reminders_occasion_check check (occasion in ('birthday','anniversary','celebration','other')),
  constraint special_date_reminders_month_check check (event_month between 1 and 12),
  constraint special_date_reminders_day_check check (
    event_day between 1 and
      case
        when event_month = 2 then 29
        when event_month in (4,6,9,11) then 30
        else 31
      end
  ),
  constraint special_date_reminders_days_before_check check (reminder_days_before between 0 and 60),
  constraint special_date_reminders_notes_check check (notes is null or char_length(notes) <= 300)
);

create index if not exists special_date_reminders_user_calendar_idx
  on public.special_date_reminders (user_id, active, event_month, event_day);

alter table public.special_date_reminders enable row level security;

revoke all on table public.special_date_reminders from public, anon, authenticated;
grant select, insert, update, delete on table public.special_date_reminders to authenticated;

do $$
begin
  if to_regclass('public.special_date_reminders_id_seq') is not null then
    execute 'revoke all on sequence public.special_date_reminders_id_seq from public, anon, authenticated';
    execute 'grant usage, select on sequence public.special_date_reminders_id_seq to authenticated';
  end if;
end $$;

drop policy if exists "Users can view own special dates" on public.special_date_reminders;
create policy "Users can view own special dates"
on public.special_date_reminders
for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "Users can add own special dates" on public.special_date_reminders;
create policy "Users can add own special dates"
on public.special_date_reminders
for insert
to authenticated
with check (user_id = (select auth.uid()));

drop policy if exists "Users can update own special dates" on public.special_date_reminders;
create policy "Users can update own special dates"
on public.special_date_reminders
for update
to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

drop policy if exists "Users can delete own special dates" on public.special_date_reminders;
create policy "Users can delete own special dates"
on public.special_date_reminders
for delete
to authenticated
using (user_id = (select auth.uid()));

create or replace function public.kantu_relationship_tools_health_check()
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
select jsonb_build_object(
  'healthy',
    coalesce((select c.relrowsecurity from pg_catalog.pg_class c where c.oid='public.special_date_reminders'::regclass), false)
    and coalesce((select c.relrowsecurity from pg_catalog.pg_class c where c.oid='public.favorites'::regclass), false)
    and not has_table_privilege('anon','public.special_date_reminders','SELECT')
    and not has_table_privilege('authenticated','public.special_date_reminders','TRUNCATE')
    and exists (
      select 1 from pg_catalog.pg_indexes
      where schemaname='public' and tablename='favorites'
        and indexname='favorites_user_id_product_id_key'
    ),
  'special_dates_rls', coalesce((select c.relrowsecurity from pg_catalog.pg_class c where c.oid='public.special_date_reminders'::regclass), false),
  'favorites_rls', coalesce((select c.relrowsecurity from pg_catalog.pg_class c where c.oid='public.favorites'::regclass), false),
  'special_dates_anon_blocked', not has_table_privilege('anon','public.special_date_reminders','SELECT'),
  'special_dates_no_truncate', not has_table_privilege('authenticated','public.special_date_reminders','TRUNCATE'),
  'favorites_unique_user_product', exists (
      select 1 from pg_catalog.pg_indexes
      where schemaname='public' and tablename='favorites'
        and indexname='favorites_user_id_product_id_key'
    )
);
$$;

revoke all on function public.kantu_relationship_tools_health_check() from public, anon, authenticated;
grant execute on function public.kantu_relationship_tools_health_check() to service_role;
