-- Kantu Floral: recordatorios opt-in de fechas importantes.
-- Privacidad mínima: no se almacena año de nacimiento, solo mes/día y una etiqueta elegida por el cliente.

create table if not exists public.occasion_reminders (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  label text not null,
  occasion_type text not null default 'special',
  month smallint not null,
  day smallint not null,
  lead_days smallint not null default 7,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint occasion_reminders_label_check check (char_length(btrim(label)) between 1 and 80),
  constraint occasion_reminders_type_check check (occasion_type in ('birthday', 'anniversary', 'special')),
  constraint occasion_reminders_lead_days_check check (lead_days between 0 and 60),
  constraint occasion_reminders_month_day_check check (
    (month in (1,3,5,7,8,10,12) and day between 1 and 31)
    or (month in (4,6,9,11) and day between 1 and 30)
    or (month = 2 and day between 1 and 29)
  )
);

create unique index if not exists occasion_reminders_user_identity_unique
  on public.occasion_reminders (user_id, lower(btrim(label)), occasion_type, month, day);
create index if not exists occasion_reminders_user_enabled_idx
  on public.occasion_reminders (user_id, enabled, month, day);

alter table public.occasion_reminders enable row level security;

revoke all on table public.occasion_reminders from public, anon, authenticated;
grant select, insert, update, delete on table public.occasion_reminders to authenticated;

do $$
begin
  if to_regclass('public.occasion_reminders_id_seq') is not null then
    execute 'revoke all on sequence public.occasion_reminders_id_seq from public, anon, authenticated';
    execute 'grant usage, select on sequence public.occasion_reminders_id_seq to authenticated';
  end if;
end $$;

drop policy if exists "Customers can read own occasion reminders" on public.occasion_reminders;
create policy "Customers can read own occasion reminders"
on public.occasion_reminders
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Customers can create own occasion reminders" on public.occasion_reminders;
create policy "Customers can create own occasion reminders"
on public.occasion_reminders
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Customers can update own occasion reminders" on public.occasion_reminders;
create policy "Customers can update own occasion reminders"
on public.occasion_reminders
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Customers can delete own occasion reminders" on public.occasion_reminders;
create policy "Customers can delete own occasion reminders"
on public.occasion_reminders
for delete
to authenticated
using (auth.uid() = user_id);

create or replace function private.normalize_occasion_reminder()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.label := btrim(new.label);
  new.updated_at := now();
  return new;
end;
$$;

revoke all on function private.normalize_occasion_reminder() from public, anon, authenticated;

drop trigger if exists occasion_reminders_normalize on public.occasion_reminders;
create trigger occasion_reminders_normalize
before insert or update
on public.occasion_reminders
for each row
execute function private.normalize_occasion_reminder();

create or replace function private.next_occasion_date(
  p_month integer,
  p_day integer,
  p_from date
)
returns date
language plpgsql
immutable
set search_path = ''
as $$
declare
  v_year integer;
  v_candidate date;
begin
  if p_from is null then return null; end if;

  for v_year in extract(year from p_from)::integer..(extract(year from p_from)::integer + 8)
  loop
    begin
      v_candidate := make_date(v_year, p_month, p_day);
    exception when datetime_field_overflow then
      continue;
    end;

    if v_candidate >= p_from then
      return v_candidate;
    end if;
  end loop;

  return null;
end;
$$;

revoke all on function private.next_occasion_date(integer,integer,date) from public, anon, authenticated;

create or replace function public.get_my_occasion_reminders()
returns table(
  id bigint,
  label text,
  occasion_type text,
  month smallint,
  day smallint,
  lead_days smallint,
  enabled boolean,
  next_occurrence date,
  days_until integer,
  is_due boolean
)
language sql
stable
security invoker
set search_path = ''
as $$
  with local_today as (
    select timezone('America/Lima', now())::date as today
  )
  select
    r.id,
    r.label,
    r.occasion_type,
    r.month,
    r.day,
    r.lead_days,
    r.enabled,
    n.next_occurrence,
    (n.next_occurrence - t.today)::integer as days_until,
    (
      r.enabled
      and n.next_occurrence is not null
      and (n.next_occurrence - t.today) between 0 and r.lead_days
    ) as is_due
  from public.occasion_reminders r
  cross join local_today t
  cross join lateral (
    select private.next_occasion_date(r.month, r.day, t.today) as next_occurrence
  ) n
  where r.user_id = auth.uid()
  order by
    r.enabled desc,
    n.next_occurrence nulls last,
    lower(r.label),
    r.id;
$$;

revoke all on function public.get_my_occasion_reminders() from public, anon;
grant execute on function public.get_my_occasion_reminders() to authenticated, service_role;

create or replace function public.kantu_occasion_reminders_health_check()
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
with rpc_state as (
  select coalesce((
    select not p.prosecdef
    from pg_catalog.pg_proc p
    join pg_catalog.pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.oid = to_regprocedure('public.get_my_occasion_reminders()')
  ), false) as is_invoker
), policy_state as (
  select count(*)::integer as policy_count
  from pg_catalog.pg_policies p
  where p.schemaname = 'public'
    and p.tablename = 'occasion_reminders'
)
select jsonb_build_object(
  'healthy',
    coalesce((select c.relrowsecurity from pg_catalog.pg_class c where c.oid='public.occasion_reminders'::regclass), false)
    and (select policy_count from policy_state) >= 4
    and to_regprocedure('public.get_my_occasion_reminders()') is not null
    and (select is_invoker from rpc_state)
    and not has_table_privilege('anon', 'public.occasion_reminders', 'SELECT')
    and has_table_privilege('authenticated', 'public.occasion_reminders', 'SELECT')
    and has_table_privilege('authenticated', 'public.occasion_reminders', 'INSERT')
    and has_table_privilege('authenticated', 'public.occasion_reminders', 'UPDATE')
    and has_table_privilege('authenticated', 'public.occasion_reminders', 'DELETE'),
  'rls', coalesce((select c.relrowsecurity from pg_catalog.pg_class c where c.oid='public.occasion_reminders'::regclass), false),
  'own_row_policies', (select policy_count from policy_state) >= 4,
  'customer_rpc', to_regprocedure('public.get_my_occasion_reminders()') is not null,
  'customer_rpc_invoker', (select is_invoker from rpc_state),
  'anon_table_blocked', not has_table_privilege('anon', 'public.occasion_reminders', 'SELECT')
);
$$;

revoke all on function public.kantu_occasion_reminders_health_check() from public, anon, authenticated;
grant execute on function public.kantu_occasion_reminders_health_check() to service_role;
